# Generated by Django 4.2.8 on 2023-12-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_images_image_alter_images_pereval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
